---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: front-end.canary
    product: sockshop
    release: canary
    stage: prod
    tier: frontend
    version: "1.5"
  name: front-end.canary
  namespace: production
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: front-end.canary
      product: sockshop
      release: canary
      stage: prod
      tier: frontend
      version: "1.5"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        dynatrace/instrument: "false"
        pipeline.build: 1.5.0.3486
        pipeline.project: sockshop
        pipeline.stage: prod-canary
        sidecar.istio.io/inject: "false"
        support.channel: '#support-sockshop-frontend'
        support.contact: jane.smith@sockshop.com
      creationTimestamp: null
      labels:
        app: front-end.canary
        product: sockshop
        release: canary
        stage: prod
        tier: frontend
        version: "1.5"
    spec:
      containers:
      - image: dynatracesockshop/front-end:0.5.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: front-end
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: front-end-canary
  labels:
    app: front-end.canary
  namespace: production
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: front-end.canary
  type: LoadBalancer
