---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front-end
    product: sockshop
    release: stable
    stage: dev
    tier: frontend
    version: "1.5"
  name: front-end
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
      product: sockshop
      release: stable
      stage: dev
      tier: frontend
      version: "1.5"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        pipeline.build: 1.5.0.3486
        pipeline.project: sockshop
        pipeline.stage: dev
        sidecar.istio.io/inject: "false"
        support.channel: '#support-sockshop-frontend'
        support.contact: jane.smith@sockshop.com
      labels:
        app.kubernetes.io/name: front-end
        app.kubernetes.io/version: "1.5"
        app.kubernetes.io/part-of: sockshop
        app: front-end
        product: sockshop
        release: stable
        stage: dev
        tier: frontend
        version: "1.5"
    spec:
      containers:
      - image: dynatracesockshop/front-end:0.5.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: front-end
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 300m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 300Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    app: front-end
  namespace: dev
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: front-end
  type: LoadBalancer
