---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user
    product: sockshop
    release: stable
    stage: dev
    tier: business
    version: "1.5"
  name: user
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
      product: sockshop
      release: stable
      stage: dev
      tier: business
      version: "1.5"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        pipeline.build: 1.5.0.0073
        pipeline.project: sockshop
        pipeline.stage: dev
        sidecar.istio.io/inject: "false"
        support.channel: '#support-sockshop-services'
        support.contact: tony.stark@sockshop.com
      labels:
        app.kubernetes.io/name: user
        app.kubernetes.io/version: "1.5"
        app.kubernetes.io/part-of: sockshop
        app: user
        product: sockshop
        release: stable
        stage: dev
        tier: business
        version: "1.5"
    spec:
      containers:
      - image: dynatracesockshop/user:0.5.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: user
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
        name: tmp-volume
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
  namespace: dev
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: user
