config:
    - dev_application : "application.json"
    - production_application : "application.json"

dev_application:
    - name: "Sockshop (Dev)"

production_application:
    - name: "Sockshop (Production)"