---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shipping
    product: sockshop
    release: stable
    stage: prod
    tier: business
    version: "1.0"
  name: shipping
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
      product: sockshop
      release: stable
      stage: prod
      tier: business
      version: "1.0"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        pipeline.build: 1.0.2.0113
        pipeline.project: sockshop
        pipeline.stage: prod-stable
        sidecar.istio.io/inject: "false"
        support.channel: '#support-sockshop-services'
        support.contact: john.doe@sockshop.com
      labels:
        app.kubernetes.io/name: shipping
        app.kubernetes.io/version: "1.0"
        app.kubernetes.io/part-of: sockshop
        app: shipping
        product: sockshop
        release: stable
        stage: prod
        tier: business
        version: "1.0"
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Xms128m -Xmx512m -XX:PermSize=128m -XX:MaxPermSize=128m -XX:+UseG1GC
            -Djava.security.egd=file:/dev/urandom
        image: dynatracesockshop/shipping:0.5.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 240
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        name: shipping
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 240
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
        name: tmp-volume
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    app: shipping
  namespace: production
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: shipping
