---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        pipeline.stage: dev
        pipeline.build: 1.1.0.8367
        pipeline.project: sockshop
        support.contact: "john.doe@sockshop.com"
        support.channel: "#support-sockshop-services"
      labels:
        app: payment
        stage: dev
        release: stable
        version: "1.1"
        tier: "business"
        product: "sockshop"
    spec:
      containers:
      - name: payment
        image: dynatracesockshop/payment:0.5.0
        resources:
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: payment
  namespace: dev
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: payment