---
apiVersion: v1
kind: Namespace
metadata:
  name: loadgen
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-load-gen
  labels:
    name: backend-load-gen
  namespace: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backend-load-gen
  template:
    metadata:
      labels:
        name: backend-load-gen
    spec:
      containers:
      - name: backend-load-gen
        image: weaveworksdemos/load-test:0.1.1
        command: ["/bin/sh"]
        args: ["-c", "curl http://front-end.production.svc.cluster.local:8080/register  -H 'Content-Type: application/json; charset=utf-8' --data '{\"username\":\"user\",\"password\":\"password\"}'; echo ''; while true; do locust --host http://front-end.production.svc.cluster.local:8080 -f /config/locustfile.py --clients 2 --hatch-rate 5 --num-request 25 --no-web; sleep 10; done"]
      nodeSelector:
        beta.kubernetes.io/os: linux