apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: rabbitmq
    product: sockshop
    stage: prod
    tier: messaging
    version: "1.0"
  name: rabbitmq
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rabbitmq
      product: sockshop
      stage: prod
      tier: messaging
      version: "1.0"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        pipeline.build: 1.0.1.0005
        pipeline.project: sockshop
        pipeline.stage: prod-stable
        prometheus.io/scrape: "false"
        sidecar.istio.io/inject: "false"
        support.channel: '#support-sockshop-middleware'
        support.contact: jimmy.page@sockshop.com
      labels:
        app.kubernetes.io/name: rabbitmq
        app.kubernetes.io/version: "1.0"
        app.kubernetes.io/part-of: sockshop
        name: rabbitmq
        product: sockshop
        stage: prod
        tier: messaging
        version: "1.0"
    spec:
      containers:
      - image: rabbitmq:3.7-management
        imagePullPolicy: IfNotPresent
        name: rabbitmq
        ports:
        - containerPort: 15672
          name: management
          protocol: TCP
        - containerPort: 5672
          name: rabbitmq
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: kbudde/rabbitmq-exporter
        imagePullPolicy: Always
        name: rabbitmq-exporter
        ports:
        - containerPort: 9090
          name: exporter
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
